### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by bartrylant** [clearbold/craft-campaignmonitor-transactional#2]
I've installed this plugin and the services plugin, however, when trying to send a test email from the control panel, I get the error message the email wasn't sent.

I guess all my api key settings are correct, since the Campaign Monitor Lists plugin does work without any problems.

**Comment by bartrylant** [comment]
The pull request from Sten solves this problem.

**Comment by heymarkreeves** [comment]
Updated in v1.0.6.
